jobs:
- job: apply
  displayName: 'Apply Terraform'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: '1.0.4'
  - task: TerraformTaskV1@0
    displayName: 'Initialize Terraform'
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
  - task: TerraformTaskV1@0
    displayName: 'Apply Terraform'
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      environmentServiceName: 'aws'
